//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EffectiveRegisterForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLOGRENCI
    {
        public int OGRID { get; set; }
        public string OGRAD { get; set; }
        public string OGRMAIL { get; set; }
        public string OGRKULLANICIAD { get; set; }
        public string SIFRE { get; set; }
    }
}
